global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: netdata
  metrics_path: /api/v1/allmetrics
  params:
    format: [prometheus]
  static_configs:
    - targets: [192.168.1.89:19999]
# - job_name: cadvisor
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   honor_labels: true
#   static_configs:
#     - targets: ['cadvisor:8080']
